In [1]:
from ease4lmp.bonded_atoms import BondedAtoms

In [2]:
a = 4.05  # Gold lattice constant
b = a / 2
fcc = BondedAtoms(
    'Au',
    cell=[(0, b, b), (b, 0, b), (b, b, 0)],
    pbc=True
)

In [3]:
fcc.get_positions()

array([[0., 0., 0.]])

In [4]:
fcc.add_bond(0, 0, img2=(1,0,0))

In [5]:
fcc.get_bonds()

array([[[ 0,  1,  0,  0],
        [ 0, -1,  0,  0],
        [ 0,  0,  0,  0],
        [ 0,  0,  0,  0]]])

In [6]:
#fcc8 = fcc.repeat((2, 2, 2))
fcc8 = fcc * (2, 2, 2)

In [7]:
fcc8.get_bonds()

array([[[ 4,  0,  0,  0],
        [ 4, -1,  0,  0],
        [ 0,  0,  0,  0],
        [ 0,  0,  0,  0]],

       [[ 4,  0,  0,  0],
        [ 4, -1,  0,  0],
        [ 0,  0,  0,  0],
        [ 0,  0,  0,  0]],

       [[ 4,  0,  0,  0],
        [ 4, -1,  0,  0],
        [ 0,  0,  0,  0],
        [ 0,  0,  0,  0]],

       [[ 4,  0,  0,  0],
        [ 4, -1,  0,  0],
        [ 0,  0,  0,  0],
        [ 0,  0,  0,  0]],

       [[-4,  1,  0,  0],
        [-4,  0,  0,  0],
        [ 0,  0,  0,  0],
        [ 0,  0,  0,  0]],

       [[-4,  1,  0,  0],
        [-4,  0,  0,  0],
        [ 0,  0,  0,  0],
        [ 0,  0,  0,  0]],

       [[-4,  1,  0,  0],
        [-4,  0,  0,  0],
        [ 0,  0,  0,  0],
        [ 0,  0,  0,  0]],

       [[-4,  1,  0,  0],
        [-4,  0,  0,  0],
        [ 0,  0,  0,  0],
        [ 0,  0,  0,  0]]])

In [8]:
fcc8.change_max_bonds(2)

In [9]:
fcc8.get_bonds()

array([[[ 4,  0,  0,  0],
        [ 4, -1,  0,  0]],

       [[ 4,  0,  0,  0],
        [ 4, -1,  0,  0]],

       [[ 4,  0,  0,  0],
        [ 4, -1,  0,  0]],

       [[ 4,  0,  0,  0],
        [ 4, -1,  0,  0]],

       [[-4,  1,  0,  0],
        [-4,  0,  0,  0]],

       [[-4,  1,  0,  0],
        [-4,  0,  0,  0]],

       [[-4,  1,  0,  0],
        [-4,  0,  0,  0]],

       [[-4,  1,  0,  0],
        [-4,  0,  0,  0]]])

In [10]:
fcc8.change_max_bonds(8)

In [11]:
fcc8.get_bonds()

array([[[ 4,  0,  0,  0],
        [ 4, -1,  0,  0],
        [ 0,  0,  0,  0],
        [ 0,  0,  0,  0],
        [ 0,  0,  0,  0],
        [ 0,  0,  0,  0],
        [ 0,  0,  0,  0],
        [ 0,  0,  0,  0]],

       [[ 4,  0,  0,  0],
        [ 4, -1,  0,  0],
        [ 0,  0,  0,  0],
        [ 0,  0,  0,  0],
        [ 0,  0,  0,  0],
        [ 0,  0,  0,  0],
        [ 0,  0,  0,  0],
        [ 0,  0,  0,  0]],

       [[ 4,  0,  0,  0],
        [ 4, -1,  0,  0],
        [ 0,  0,  0,  0],
        [ 0,  0,  0,  0],
        [ 0,  0,  0,  0],
        [ 0,  0,  0,  0],
        [ 0,  0,  0,  0],
        [ 0,  0,  0,  0]],

       [[ 4,  0,  0,  0],
        [ 4, -1,  0,  0],
        [ 0,  0,  0,  0],
        [ 0,  0,  0,  0],
        [ 0,  0,  0,  0],
        [ 0,  0,  0,  0],
        [ 0,  0,  0,  0],
        [ 0,  0,  0,  0]],

       [[-4,  1,  0,  0],
        [-4,  0,  0,  0],
        [ 0,  0,  0,  0],
        [ 0,  0,  0,  0],
        [ 0,  0,  0,  0],
        [ 0,  0,  0,  0],
    

In [12]:
import ase

In [13]:
a1 = ase.Atom('Si', (0, 0, 0))

In [14]:
fcc_a1 = fcc + a1

In [16]:
fcc_a1.get_bonds()

array([[[ 0,  1,  0,  0],
        [ 0, -1,  0,  0],
        [ 0,  0,  0,  0],
        [ 0,  0,  0,  0]],

       [[ 0,  0,  0,  0],
        [ 0,  0,  0,  0],
        [ 0,  0,  0,  0],
        [ 0,  0,  0,  0]]])

In [25]:
a2 = ase.Atom('Fe', (0, 0, 0))

In [26]:
fcc_a1.append(a2)

In [27]:
fcc_a1.get_bonds()

array([[[ 0,  1,  0,  0],
        [ 0, -1,  0,  0],
        [ 0,  0,  0,  0],
        [ 0,  0,  0,  0]],

       [[ 0,  0,  0,  0],
        [ 0,  0,  0,  0],
        [ 0,  0,  0,  0],
        [ 0,  0,  0,  0]],

       [[ 0,  0,  0,  0],
        [ 0,  0,  0,  0],
        [ 0,  0,  0,  0],
        [ 0,  0,  0,  0]]])

In [17]:
a = ase.Atoms('N2', [(0, 0, 0), (0, 0, 1.104)])

In [18]:
fcc_a = fcc + a

In [19]:
fcc_a.get_bonds()

array([[[ 0,  1,  0,  0],
        [ 0, -1,  0,  0],
        [ 0,  0,  0,  0],
        [ 0,  0,  0,  0]],

       [[ 0,  0,  0,  0],
        [ 0,  0,  0,  0],
        [ 0,  0,  0,  0],
        [ 0,  0,  0,  0]],

       [[ 0,  0,  0,  0],
        [ 0,  0,  0,  0],
        [ 0,  0,  0,  0],
        [ 0,  0,  0,  0]]])

In [24]:
tmp = tmp[[True, False, True]]

In [8]:
bonds = fcc.arrays["bonds"]

In [20]:
np.resize(bonds, (5, 2, 4))

array([[[ 1,  0,  0,  0],
        [ 4, -1,  0,  0]],

       [[ 0,  0,  0,  0],
        [ 0,  0,  0,  0]],

       [[ 1,  0,  0,  0],
        [-1,  0,  0,  0]],

       [[ 0,  0,  0,  0],
        [ 0,  0,  0,  0]],

       [[ 1,  0,  0,  0],
        [-1,  0,  0,  0]]])

In [27]:
np.all(tmp[1:]==0)

True

In [12]:
-1 // 2

-1

In [11]:
tmp = [1,2,3,4,5]
a = np.array(tmp)
tmp*a

array([ 1,  4,  9, 16, 25])

In [42]:
a = np.array((2//1, 4//2, 5//3))

In [43]:
type(a[0])

numpy.int64

In [20]:
tmp = [1, 2, 3]

In [23]:
tmp([False, True, False])

TypeError: 'list' object is not callable