In [1]:
from ease4lmp.bonded_atoms import BondedAtoms

In [2]:
a = 4.05  # Gold lattice constant
b = a / 2
fcc = BondedAtoms(
    'Au',
    cell=[(0, b, b), (b, 0, b), (b, b, 0)],
    pbc=True
)

In [3]:
fcc.get_positions()

array([[0., 0., 0.]])

In [4]:
fcc.add_bond(0, 0, img2=(1,0,0))

In [5]:
fcc.get_bonds()

array([[[ 0,  1,  0,  0],
        [ 0, -1,  0,  0],
        [ 0,  0,  0,  0],
        [ 0,  0,  0,  0]]])

In [6]:
#fcc8 = fcc.repeat((2, 2, 2))
fcc8 = fcc * (2, 2, 2)

In [7]:
fcc8.get_bonds()

array([[[ 4,  0,  0,  0],
        [ 4, -1,  0,  0],
        [ 0,  0,  0,  0],
        [ 0,  0,  0,  0]],

       [[ 4,  0,  0,  0],
        [ 4, -1,  0,  0],
        [ 0,  0,  0,  0],
        [ 0,  0,  0,  0]],

       [[ 4,  0,  0,  0],
        [ 4, -1,  0,  0],
        [ 0,  0,  0,  0],
        [ 0,  0,  0,  0]],

       [[ 4,  0,  0,  0],
        [ 4, -1,  0,  0],
        [ 0,  0,  0,  0],
        [ 0,  0,  0,  0]],

       [[-4,  1,  0,  0],
        [-4,  0,  0,  0],
        [ 0,  0,  0,  0],
        [ 0,  0,  0,  0]],

       [[-4,  1,  0,  0],
        [-4,  0,  0,  0],
        [ 0,  0,  0,  0],
        [ 0,  0,  0,  0]],

       [[-4,  1,  0,  0],
        [-4,  0,  0,  0],
        [ 0,  0,  0,  0],
        [ 0,  0,  0,  0]],

       [[-4,  1,  0,  0],
        [-4,  0,  0,  0],
        [ 0,  0,  0,  0],
        [ 0,  0,  0,  0]]])

In [8]:
fcc8.change_max_bonds(2)

In [9]:
fcc8.get_bonds()

array([[[ 4,  0,  0,  0],
        [ 4, -1,  0,  0]],

       [[ 4,  0,  0,  0],
        [ 4, -1,  0,  0]],

       [[ 4,  0,  0,  0],
        [ 4, -1,  0,  0]],

       [[ 4,  0,  0,  0],
        [ 4, -1,  0,  0]],

       [[-4,  1,  0,  0],
        [-4,  0,  0,  0]],

       [[-4,  1,  0,  0],
        [-4,  0,  0,  0]],

       [[-4,  1,  0,  0],
        [-4,  0,  0,  0]],

       [[-4,  1,  0,  0],
        [-4,  0,  0,  0]]])

In [10]:
fcc8.change_max_bonds(8)

In [11]:
fcc8.get_bonds()

array([[[ 4,  0,  0,  0],
        [ 4, -1,  0,  0],
        [ 0,  0,  0,  0],
        [ 0,  0,  0,  0],
        [ 0,  0,  0,  0],
        [ 0,  0,  0,  0],
        [ 0,  0,  0,  0],
        [ 0,  0,  0,  0]],

       [[ 4,  0,  0,  0],
        [ 4, -1,  0,  0],
        [ 0,  0,  0,  0],
        [ 0,  0,  0,  0],
        [ 0,  0,  0,  0],
        [ 0,  0,  0,  0],
        [ 0,  0,  0,  0],
        [ 0,  0,  0,  0]],

       [[ 4,  0,  0,  0],
        [ 4, -1,  0,  0],
        [ 0,  0,  0,  0],
        [ 0,  0,  0,  0],
        [ 0,  0,  0,  0],
        [ 0,  0,  0,  0],
        [ 0,  0,  0,  0],
        [ 0,  0,  0,  0]],

       [[ 4,  0,  0,  0],
        [ 4, -1,  0,  0],
        [ 0,  0,  0,  0],
        [ 0,  0,  0,  0],
        [ 0,  0,  0,  0],
        [ 0,  0,  0,  0],
        [ 0,  0,  0,  0],
        [ 0,  0,  0,  0]],

       [[-4,  1,  0,  0],
        [-4,  0,  0,  0],
        [ 0,  0,  0,  0],
        [ 0,  0,  0,  0],
        [ 0,  0,  0,  0],
        [ 0,  0,  0,  0],
    

In [12]:
import ase

In [13]:
a1 = ase.Atom('Si', (0, 0, 0))

In [14]:
fcc_a1 = fcc + a1

In [15]:
type(fcc_a1)

ease4lmp.bonded_atoms.BondedAtoms

In [16]:
fcc_a1.get_bonds()

array([[[ 0,  1,  0,  0],
        [ 0, -1,  0,  0],
        [ 0,  0,  0,  0],
        [ 0,  0,  0,  0]],

       [[ 0,  0,  0,  0],
        [ 0,  0,  0,  0],
        [ 0,  0,  0,  0],
        [ 0,  0,  0,  0]]])

In [17]:
a2 = ase.Atom('Fe', (0, 0, 0))

In [18]:
fcc_a1.append(a2)

In [19]:
fcc_a1.get_bonds()

array([[[ 0,  1,  0,  0],
        [ 0, -1,  0,  0],
        [ 0,  0,  0,  0],
        [ 0,  0,  0,  0]],

       [[ 0,  0,  0,  0],
        [ 0,  0,  0,  0],
        [ 0,  0,  0,  0],
        [ 0,  0,  0,  0]],

       [[ 0,  0,  0,  0],
        [ 0,  0,  0,  0],
        [ 0,  0,  0,  0],
        [ 0,  0,  0,  0]]])

In [20]:
a = ase.Atoms('N2', [(0, 0, 0), (0, 0, 1.104)])

In [21]:
fcc_a = fcc + a

In [22]:
fcc_a.get_bonds()

array([[[ 0,  1,  0,  0],
        [ 0, -1,  0,  0],
        [ 0,  0,  0,  0],
        [ 0,  0,  0,  0]],

       [[ 0,  0,  0,  0],
        [ 0,  0,  0,  0],
        [ 0,  0,  0,  0],
        [ 0,  0,  0,  0]],

       [[ 0,  0,  0,  0],
        [ 0,  0,  0,  0],
        [ 0,  0,  0,  0],
        [ 0,  0,  0,  0]]])

In [25]:
fcc5 = fcc.repeat((5, 1, 1))

In [26]:
fcc5.get_bonds()

array([[[ 1,  0,  0,  0],
        [ 4, -1,  0,  0],
        [ 0,  0,  0,  0],
        [ 0,  0,  0,  0]],

       [[ 1,  0,  0,  0],
        [-1,  0,  0,  0],
        [ 0,  0,  0,  0],
        [ 0,  0,  0,  0]],

       [[ 1,  0,  0,  0],
        [-1,  0,  0,  0],
        [ 0,  0,  0,  0],
        [ 0,  0,  0,  0]],

       [[ 1,  0,  0,  0],
        [-1,  0,  0,  0],
        [ 0,  0,  0,  0],
        [ 0,  0,  0,  0]],

       [[-4,  1,  0,  0],
        [-1,  0,  0,  0],
        [ 0,  0,  0,  0],
        [ 0,  0,  0,  0]]])

In [20]:
fcc5.pop(2)

array([[[ 1,  0,  0,  0],
        [ 4, -1,  0,  0]],

       [[ 0,  0,  0,  0],
        [ 0,  0,  0,  0]],

       [[ 1,  0,  0,  0],
        [-1,  0,  0,  0]],

       [[ 0,  0,  0,  0],
        [ 0,  0,  0,  0]],

       [[ 1,  0,  0,  0],
        [-1,  0,  0,  0]]])

In [12]:
import numpy as np

In [25]:
a = np.arange(10)

In [30]:
a[9:-1] = a[9:]

In [33]:
a[-1] = 10

In [41]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8, 10])

In [35]:
mask = np.ones(10, bool)

In [45]:
mask[np.array([2, 3, 4, 5])] = False

In [51]:
np.sum(mask != True)

4